### PR TITLE
Suggested Solution to Apply with LinkedIn hiding Submit and Cancel Buttons

### PR DESCRIPTION
**Pull request by bulbajackel**
Currently, on lower resolution monitors such as 1366 x 768 and below, the send and cancel buttons are out of view.   An example can be found in #41 
## Additions

- I have added the Apply with LinkedIn Button to the right side detail card.

## Removals

- The Apply with Linkedin Button from the Application Modal.
- I removed the formatting on the alert dialogue to retry the LinkedIn integration   (This also reduces the size of the modal and it isn't aesthetically abrasive)  
- Removed 5 Rows from the Skills & Work Experience field to fit on the lower resolution screens.

## Testing

- Tested in Chrome in Multiple Resolutions
  - on a 1366 x 768 laptop display
  - Emulating 1100 x 799 resolution
  - emulating 1280 x 720
- Tested in Multiple Mobile Resolutions 
  - 360 x 640
  - 435 x 773
  -  768 x 1024 
- I have ran the gulp test and gulp protractor and have not received any errors

## Review

- Anyone, please let me know if you have any questions or Suggestions

### Before (courtesy of the creator of 41)

image

image

### After

image

image

## Notes

- This solution reduces the number of clicks to apply to a job.  
- This is also important becuase a large majority of mid to low end laptops or older laptops 3 years or older are at or below the resolutions that this pull request fixes.  

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [contributing guide](https://github.com/bullhorn/career-portal/blob/master/CONTRIBUTING.md)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices

### CODE REVIEW

**Comment by krsween** [comment]
Hey, @bulbajackel—

Nice work on this so far! I do like where this is headed. I did have a thought: Do you like having the LinkedIn pop-up warning message contained in the modal now that the apply button is on the details page? I saw the styles were moved to the details controller, but not that little piece of text. I wonder how that would look. What are your thoughts?

Nice work on this!
K.

**Comment by bulbajackel** [comment]
I did move the warning message to the detail originally,  however when the modal appears the container darkens the warning message, removing attention away from it. Also I would have had to switch the container for the modal to have "pointer event: none;" so you could click through to retry.  That seemed a bit messy to me. 

Another reason I left it on the modal is for the mobile users, they will not be able to retry without it remaining on the modal page.  I am extremely open to suggestions however.  Another thought I had was to wait on opening the LinkedIn Modal until the data has been added from the LinkedIn API, but I was not too sure on that.

**Comment by krsween** [comment]
Good points! In order for that UX to work, we would need to make sure that the LinkedIn data was present before firing off the modal. Could you wrap the open modal logic in a promise to prevent it from opening unless (1) there was data provided from LinkedIn or (2) the user wanted to organically apply?

Also, we'll want to disable both when the user has applied.

**Comment by bulbajackel** [comment]
I have added the logic to the PR.   I restricted the modal from opening in "modal.controller.js" unless the user is loaded.   I also added to the LinkedIn service "this.SharedData.modalState = 'open';"  to open the modal when the user is loaded.  

As Always, I'm open to input, please let me know if you have any more questions/suggestions

**Comment by developergoutam** [comment]
Hi there I have deployed the latest version career-portal-v1.5.0.zip
But fetched a problem with Apply with LinkedIn Option.

Error Message "Heads Up! If the LinkedIn sign in page does not appear shortly, please make sure your browser allows pop-ups. Click here to retry."
though my browser allows pop-ups.

Please guide me.

**Comment by krsween** [comment]
Are you running this locally or on a server?

**Comment by developergoutam** [comment]
@krsween I have deployed it on Server. 
IP Details.
http://54.221.230.11:8080/career-portal/
you can also check the error from your browser.

**Comment by john-pennington** [comment]
@developergoutam In order to activate your Apply with LinkedIn integration, you must whitelist development and production environment IP addresses and/or hostnames with the application you created at LinkedIn Developer. In your case you would whitelist http://54.221.230.11:8080.

Can you verify this? Sign into https://www.linkedin.com, navigate to https://www.linkedin.com/developer/apps, select your app, and click 'JavaScript' in the lefthand menu to see the valid SDK domains you've whitelisted.

**Comment by developergoutam** [comment]
@john-pennington 
Thank you very much for your kind help.
Thank you again....

**Comment by kolagotlaa** [comment]
Thanks @john-pennington and @developergoutam. Your suggestions helped me solve the intial problem of getting Apply with LI to work. I was getting the popup error. Once I added the career url to the "Valid SDK domain", that solved the issue.

Now I am able to get the LI sign-in popup, upon sign-in LI sends Name, email and description to the bullhorn apply page. But upon clicking "Submit" I get the following error (see pic below):

"There was an error when applying. Try again" 

linkedin bullhorn error

Seems to me like a Bullhorn error. Can one of you help with this.

**Comment by kolagotlaa** [comment]
Ok, so I called BH Support and seems like the issue occurs when someone who already has a record in our system applies. Any ideas on how to resolve this issue?

**Comment by kbushkoBH** [comment]
Hi kolagotlaa,

Apologies for any confusion on this - the behavior you have observed should only occur when the email address used with the application is associated to a deleted candidate record in your Bullhorn system. You may wish to follow that open issue here, as it is unrelated to Apply with LinkedIn: https://github.com/bullhorn/career-portal/issues/51

If you are logged into Bullhorn, you can observe the deleted candidate that caused the error you received by navigating to this URL in the same browser session: https://www.bullhornstaffing.com/BullhornStaffing/OpenWindow.cfm?Entity=Candidate&id=1367

(Your specific candidate will not be visible to Bullhorn users on other instances with this link.)

Here is the basic overview of how applications should be processed:
1 - If an applicant submits their resume with an email address that is not already on a candidate record in your system, the candidate record is created. 
2 - If an applicant submits their resume with an email address that is already associated to a candidate record, their new resume is added to the existing record's files tab, and each job they apply to is recorded. You also have the option for a returning applicant's most recently submitted resume to be automatically parsed to their record. 
3 - If a candidate applies whose email address is associated to a deleted candidate record, as above, an error occurs and the application is not processed. As a best practice, we recommend removing email addresses from deleted records, or using a status value to indicate the candidate is unfit/inactive, rather than deleting the record. This will prevent the behavior you have observed.

**Comment by kolagotlaa** [comment]
Thanks a bunch @kbushkoBH. Its helpful to know that the issue occurs only in the case of deleted candidates.

**Pull request merged**
