### PR TITLE
Fix for missing non-English characters in jobs list descriptions.

### PR DESCRIPTION
**Pull request by EricNLecuyer**
When my client wrote a job description in French in Bullhorn's backend, all the non-English characters were filtered out in the excerpt. 

### Example 
*"Une entreprise réputée est à la recherche d’une Adjointe pour son Président."*

**Came out like this:**

*"Une entreprise rpute est la recherche d’une Adjointe pour son Prsident."*

## Solution
Since I never worked with Angular before, I wanted to play it safe. Not knowing if stripHtml was used for other purposes (like urls), I made a copy named stripDescHtml and added all the French characters in the switch. 

There is probably a simpler solution, but this one fixed the problem so far.

## Options
If there is no better option and stripHtml is (and will be) only used on the jobs list descriptions, I guess the missing characters could be added there instead of a new filter.

### CODE REVIEW

**Comment by krsween** [comment]
Hey, @EricNLecuyer—

Thanks so much for your contribution. I was wondering if you had tried using [ngBind](https://docs.angularjs.org/api/ng/directive/ngBind) or [ngBindHtml](https://docs.angularjs.org/api/ng/directive/ngBindHtml)? I'm not 100% sure that would work, but I think it's worth a shot. 

If that doesn't work, then I'd be happy to move forward in this direction. At a glance, the only thing I'd alter is using `let` instead of `var`. If we run ngBind aground, then we can work together to get this merged into OSCP.

Thanks again for the contribution!

**Comment by EricNLecuyer** [comment]
My pleasure! I have to do another implementation this week so I'll be able to do more tests. 

So far,`ng-bind` returns raw html, but `ng-bind-html` works very well even without a filter! It returns the full formatted text along with the non-English characters, so I'm pretty sure that this is the way to go. Thanks for the suggestion!

My only concern is that it doesn't remove line breaks and that the entire description is shown in list view (grid view is fine). I'll try to fix it with SCSS this week and I'll let you know.

Thanks again for your help!

**Comment by krsween** [comment]
Have you tried modifying the following properties?

```
white-space: normal;
word-break: break-all;
```

These may help get the line-breaks back in order. If you point me to a live instance (URL) with the broken line-breaks, I can try a few other things to get the lines to break correctly.

**Comment by EricNLecuyer** [comment]
It didn't work so far. Here is the link : [L'indispensable](http://jobs.lindispensable.com/#/jobs)

**Comment by krsween** [comment]
gppx5e33qd

Which browser are you using? It looks fine for me, so our environments must be different. I'm Chrome (edge) on OSX.

**Comment by EricNLecuyer** [comment]
I'm on Firefox and Chromium in Ubuntu. The list-view descriptions are hidden on sizes smaller than large. 

Here is what I see:

#### List view
list-view

#### Grid view
grid-view

**Comment by krsween** [comment]
Oh! If I'm understanding correctly, this is a feature, haha. Arguably not a flawless one at that. 

We're fixing the height of those 'cards' to make them grid-like. Some of the content will always be clipped to prevent the cards from becoming floor to ceiling wall-paper. Does that make sense? To change that you can modify the height of those cards, but likely there will always be some clipping of the content.

**Comment by EricNLecuyer** [comment]
Haha no the cards are great! :-)

Using `ng-bind-html` would give more control to the users since they can format their excerpts before publishing the job. While this is a great feature in my view, I wonder how it would affect, after a portal update, users who never changed their description before publishing, expecting it to be joined in the same line without formatting.

Here is what I see with the current `<span class="card-description">{{::job.publicDescription | stripHtml}}</span>`
capture du 2016-08-24 10 39 41
capture du 2016-08-24 10 39 45


And here is the new, improved but different `<span class="card-description" ng-bind-html="job.publicDescription"></span>`
capture du 2016-08-24 10 40 03
capture du 2016-08-24 10 40 05


Hence, ng-bind-html would fix a localization issue while giving more control to the users. Still, the former is not always a good thing :-)

**Comment by krsween** [comment]
>new, improved but different

I want this on a t-shirt. 

Another word for this is 'verschlimmbesserung', which is an alleged improvement that makes things worse than they already were. Anyway...

This is respecting Bullhorn's HTML, which I think (as an enhancement to OSCP) it should. I believe most users would want to prescribe their published job HTML inside of our platform and see that rendered/respected in OSCP. But, like most solutions, it does create a little bit of a dilemma that your code (filter) solves. 

For your portal, it seems like the solution you put together works a lot nicer, but I really like the improvement you made to more accurately render the HTML, and I'd like to merge that into OSCP on this Pull Request (PR) because I think all users would benefit from that. I think the other solution solves a more niche problem, but it solves it a lot better. Could we update this PR to contain ng-bind-html change?

**Comment by EricNLecuyer** [comment]
Hahaha! 

Great, I'm glad this helped. If it's ok, I would remove the `StripDescHtml` filter altogether since `ng-bind-html` fixes the problem anyway. The new filter solution would also be quite tedious to scale: if we wanted to make it work for more languages than French, we would have to include...well...almost all of [these](http://unicode-table.com/fr/#control-character) :-S

**Comment by krsween** [comment]
Thanks @EricNLecuyer! This is a smart addition. 

You're absolutely right about maintaining large-scale resolutions being problematic. I'm working on an i18n library for Angular 2 called [Chomsky](https://github.com/bullhorn/chomsky/) and the pluralization piece was where I realized I wanted nothing to do with infinite property files so we solved (for now) pluralization without using any static properties.

Best of luck on your portal. Feel free to reach out with questions as they arise. Thanks for your contribution to OSCP!

**Pull request merged**
